In [23]:
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd 
import matplotlib.pyplot as plt
import os

In [4]:
file_path=os.path.expanduser("~/AI_Engineer/04_Data_Vault/Data_Projects/Medical_Insurance/medical_insurance.csv")

In [7]:
df=pd.read_csv(file_path)

In [37]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [41]:
df.describe()

               age          bmi     children       charges
count  2772.000000  2772.000000  2772.000000   2772.000000
mean     39.109668    30.701349     1.101732  13261.369959
std      14.081459     6.129449     1.214806  12151.768945
min      18.000000    15.960000     0.000000   1121.873900
25%      26.000000    26.220000     0.000000   4687.797000
50%      39.000000    30.447500     1.000000   9333.014350
75%      51.000000    34.770000     2.000000  16577.779500
max      64.000000    53.130000     5.000000  63770.428010

In [42]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       2772 non-null   int64
 1   sex       2772 non-null   object
 2   bmi       2772 non-null   float64
 3   children  2772 non-null   int64
 4   smoker    2772 non-null   object
 5   region    2772 non-null   object
 6   charges   2772 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 151.7+ KB
None

In [43]:
df_encoded=pd.get_dummies(df,drop_first=True)
X=df_encoded.drop(['charges'],axis=1)
y=df_encoded['charges']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print(f"the counter of training data is : {X_train.shape[0]}")
print(f"the counter of testing data is :  {X_test.shape[0]}")

the counter of training data is : 2217
the counter of testing data is :  555

In [44]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
print(f"this is the first part of this operater:\n{X_train_scaled[0]}")

this is the first part of this operater:
[-1.3144233   1.00536512 -0.91183384  0.97902021 -0.51447945 -0.56606433
  1.63790239 -0.5716209 ]